language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_install:
  - sudo runuser -l postgres -c "/usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main -l logfile restart"
  - sudo runuser -l postgres -c "psql -p 5433 -c $'ALTER ROLE postgres WITH PASSWORD \'postgres\'; '"
  - sudo sed -i 's/peer/md5/' /etc/postgresql/12/main/pg_hba.conf
  - sudo runuser -l postgres -c "/usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main -l logfile restart"
before_script:
  - psql -c 'create database "dev-lft-test";' -U postgres -w -p 5433
  - for f in ./migrations/*.do.*; do psql -d $TEST_DB_URL -p 5433 -U postgres -w -f $f ;done
