language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_install:
  - sudo runuser -l postgres -c "psql -c 'ALTER ROLE postgres WITH PASSWORD \'postgres\'' 
  - sudo sed -i 's/peer/md5/' /etc/postgresql/12/main/pg_hba.conf
  - sudo runuser -l postgres -c "/usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main -l logfile restart"
before_script:
  - psql -c 'create database "dev-lft-test";' -U postgres -w -p 5433
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/001.do.create_users.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/002.do.create_projects_vacancies.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/003.do.create-requests.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/004.do.create-posts.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/005.do.create_chats_messages.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/006.do.create_notifications.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/007.do.alter_requests.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/008.do.remove_project_id.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/009.do.alter_chats.sql
  - psql -d $TEST_DB_URL -U postgres -f ./migrations/010.do.alter_projects.sql
